### ISSUE TITLE
[JOSS Review] Software / documentation

### ISSUE THREAD

**Issue by AnnikaStein** [thraraujo/pysymmpol#1]
- [x] Syntax error in the last line of https://thraraujo.github.io/pysymmpol/getting-started.html#homogeneous-and-elementary-polynomials
- [x] https://thraraujo.github.io/pysymmpol/pysymmpol.html#module-pysymmpol Module contents is empty, do you need this heading then?

tbc, as the review progresses:

https://github.com/openjournals/joss-reviews/issues/6724

**Comment by thraraujo** [comment]
Hi @AnnikaStein, I've fixed a couple of typos in the documentation, and also corrected what you suggested here.

**Comment by thraraujo** [comment]
Hi @AnnikaStein, one last thing.

While I acknowledge the suggestion to test the software in other environments, I believe it might be overly cautious given the package's minimal dependencies. It's worth noting that the dependencies are not brand new releases.

**Comment by thraraujo** [comment]
Dear @AnnikaStein, today I've checked the dependencies. It turns out that it works for python 3.11, sympy 1.11. I have not checked earlier versions. Numpy below 1.26.2 does not run. I have updated the README file and the documentation. It is in the main branch.

**Comment by AnnikaStein** [comment]
Very nice, thank you for working on these! Feel free to close this issue.
