### ISSUE TITLE
[JOSS Review] Type Annotations and CI

### ISSUE THREAD

**Issue by eliotwrobson** [thraraujo/pysymmpol#2]
The code for this library looks pretty clean, but I think it would benefit from adding visible type annotations. Many functions have annotations already, and making these visible to client code would help usability of the package. For information on this, have a look here: https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/

You should be able to do this just by making the new file, since poetry picks up this file by default.

Similarly, these annotations should be checked for correctness in the CI job, along with running the existing tests. For a short example of this in a GitHub workflow, see here (disclaimer: This comes from a project I worked on): https://github.com/eliotwrobson/CyNetDiff/blob/main/.github/workflows/tests.yml

This repo also seems like a nice example: https://github.com/LaurenceRawlings/python-poetry-cicd

From review https://github.com/openjournals/joss-reviews/issues/6724

**Comment by thraraujo** [comment]
Dear Eliot, thanks. 

This is done, check the main branch. Github actions worked smoothly. See here: https://github.com/thraraujo/pysymmpol/actions/runs/9009994398

**Comment by eliotwrobson** [comment]
Output from new actions looks great! Will close.

**Comment by eliotwrobson** [comment]
@thraraujo I think the `py.typed` file needs to be in the `pysymmpol` folder, as this is the package directory (while the root of the repository is not).
