### ISSUE TITLE
[JOSS Review] Minor Nitpicks

### ISSUE THREAD

**Issue by eliotwrobson** [thraraujo/pysymmpol#4]
Just some small miscellaneous things I noticed:

- [ ] On this line, the check can be changed to `isinstance(self.partition, (tuple, np.ndarray))`: https://github.com/thraraujo/pysymmpol/blob/main/pysymmpol/partitions/young.py#L33

See https://stackoverflow.com/a/33311330
- [ ] Similarly, the `all` function can be called on a generator expression instead of a list, and using the slice here makes a copy: https://github.com/thraraujo/pysymmpol/blob/main/pysymmpol/partitions/young.py#L39

It would be better to have `A = all(x >= y for x,y in pairwise(par))`, avoiding the issues mentioned above.

- [ ] In this same file (and other places), you use the raw `tuple` type annotation, when you really only want tuples that contain numbers. This can be done with the annotation `tuple[numbers.Number, ...]`, indicating an indeterminate length tuple containing only numbers: https://stackoverflow.com/a/4187266

Similarly specific annotations can be done with a lot of the `dict` annotations in the package as well.

- [ ] In the `count_diagonal` function, you create a whole matrix and then compute the trace: https://github.com/thraraujo/pysymmpol/blob/main/pysymmpol/partitions/young.py#L88

However, all you are doing in the inner loop is constructing a row of `partition[n]` ones and padding with zeros, which is wasteful for large diagrams. Instead, you can just iterate through each row of the diagram and add 1 to your final result if `partition[n] >= n`, indicating that there would be a 1 on the diagonal. In fact, I think this is done by the one-liner `sum(1 if part >= n else 0 for n, part in enumerate(partition))`, as this adds 1 for each row in the diagram that crosses the diagonal.

- [ ] I like your statement of need from the paper you submitted, but this should be made part of the documentation + README.md as well.

Part of the ongoing JOSS review: https://github.com/openjournals/joss-reviews/issues/6724

**Comment by thraraujo** [comment]
Hi @eliotwrobson,

Thank you once again. Regarding the other issue, I've made significant updates to the count diagonal and Frobenius coordinates methods. Now, I've completely revamped the approach. Initially, I compute the Frobenius coordinates through a loop, utilizing both physicist and mathematician definitions. Once these expressions are derived, I proceed to calculate the diagonal terms based on the length of these coordinates. Additionally, I've implemented some tests to ensure accuracy, and I verify the number of boxes in the diagonal using hook lengths to validate the results. 

I'll revisit the remaining points on Monday. Thanks again

**Comment by eliotwrobson** [comment]
Awesome! I think the new code computing this recomputes the transpose repeatedly in the inner loop, so you should store this in a variable if you can, but otherwise looks much cleaner that before 👍👌

**Comment by thraraujo** [comment]
well noticed! fixed.

**Comment by thraraujo** [comment]
Hi @eliotwrobson,

I wanted to share some (in my opinion) positive updates:

1. Upon reviewing volume 4 of TAOCP, I came across an interesting relationship between the conjugate of a Young diagram and its conjugacy representation. Leveraging this connection, I've revamped the method for calculating the transpose, resulting in a significant improvement.

2. Additionally, I've addressed the other points you raised. Thank you for those suggestions; I found them quite beneficial, especially the 'pairwise' tip.

3. I might have overlooked something, but I do agree with the necessity of validating the type. I've implemented it differently, though.

4. The review has been included in the readme. However, I haven't yet added it to the documentation. I plan to do so in the future; I just need to figure out how to incorporate LaTeX support into Sphinx. It's likely straightforward, but I prefer not to delve into that at the moment.

**Comment by eliotwrobson** [comment]
@thraraujo that all sounds excellent! None of these items were hard review blockers (besides the statement of need), just things I noticed that could possibly clean up parts of the package. If you're satisfied with changes made based on my suggestions, feel free to close this issue 😃

**Comment by thraraujo** [comment]
@eliotwrobson, thanks... In fact, I was just checking the statement of need. I didn't like the way sphinx adds math support, so I created a link to the repo. Case closed!
