### ISSUE TITLE
[JOSS Review] Documentation

### ISSUE THREAD

**Issue by eliotwrobson** [thraraujo/pysymmpol#6]
The documentation includes the functions and classes in the `tests` folder, even though these are not part of the package. These should be removed: https://thraraujo.github.io/pysymmpol/tests.html

Additionally, the test uses the unittest class inheritance structure, instead of the just the cleaner naming convention traditionally used by pytest (no need for the wrapper classes). However, feel free to ignore this since it requires changing the way assertions need to be done, but still something to keep in mind.

Part of https://github.com/openjournals/joss-reviews/issues/6724

**Comment by thraraujo** [comment]
Hi @eliotwrobson 

I removed the test from the documentation.

Regarding the second point; some of these tests were implemented before incorporating pytest into my workflow. For consistency's sake, I'd rather not retroactively modify these tests. In future projects I can use pytest standards from the outset.

**Comment by eliotwrobson** [comment]
@thraraujo looks good! As I said, the test format changes were not blocking, so I will go ahead and close.
